Fix comments being disabled causing an error.
If comments are disabled in `luaparse` through the secondary `options` parameter, there is no `comments` array defined, which causes the error below. This error occurs regardless of comments being present or absent in the code.

> TypeError: Cannot read property 'map' of undefined

Example code:

```javascript
const luaparse = require('luaparse');
const codegen = require('luacodegen');

const code = 'print(true)';

const ast = luaparse.parse(code, {'comments': false});
const formatted = codegen(ast);

console.log(formatted);
```